# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box_check_update = false

  # ============ Контроллер Ansible на AlmaLinux 8 =============
  config.vm.define "ansible-controller" do |controller|
    controller.vm.box = "generic/alma8"
    controller.vm.hostname = "controller"

    controller.vm.network "private_network", ip: "192.168.56.10"

    controller.vm.provision "shell", inline: <<-SHELL
      sudo dnf -y update
      sudo dnf -y install epel-release
      sudo dnf -y install ansible
    SHELL
  end

  # ============ Ubuntu Server =============
  config.vm.define "ubuntu-server1" do |server1|
    server1.vm.box = "ubuntu/focal64"
    server1.vm.hostname = "ubuntu-server1"

    server1.vm.network "public_network"
    server1.vm.network "private_network", ip: "192.168.56.11"

    server1.vm.provision "shell", inline: <<-SHELL
      sudo apt-get update -y
    SHELL
  end
end
